### ISSUE TITLE
execute `bytomd node` got an error

### ISSUE THREAD

**Issue by shellteo** [Bytom/bytom#1821]
go: go1.13.5 linux/amd64
os: ubuntu 18.04

error message
```
all logs are output in the /home/zx/.bytom/log directory
panic: Panicked on a Sanity Check: Error initializing DB: resource temporarily unavailable

goroutine 1 [running]:
github.com/bytom/vendor/github.com/tendermint/tmlibs/common.PanicSanity(...)
	/home/zx/go/src/github.com/bytom/vendor/github.com/tendermint/tmlibs/common/errors.go:26
github.com/bytom/database/leveldb.NewDB(0xdfd4cb, 0x4, 0xc0001e68f0, 0x7, 0xc0002b6360, 0x14, 0xc0001600d0, 0xc773db)
	/home/zx/go/src/github.com/bytom/database/leveldb/db.go:62 +0x237
github.com/bytom/node.NewNode(0xc00027a000, 0x0)
	/home/zx/go/src/github.com/bytom/node/node.go:81 +0x1e2
github.com/bytom/cmd/bytomd/commands.runNode(0x1be5060, 0x1c13608, 0x0, 0x0, 0x0, 0x0)
	/home/zx/go/src/github.com/bytom/cmd/bytomd/commands/run_node.go:85 +0x81
github.com/bytom/vendor/github.com/spf13/cobra.(*Command).execute(0x1be5060, 0x1c13608, 0x0, 0x0, 0x1be5060, 0x1c13608)
	/home/zx/go/src/github.com/bytom/vendor/github.com/spf13/cobra/command.go:698 +0x42c
github.com/bytom/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1be4e40, 0xc000163ea0, 0xe1e27b, 0x24)
	/home/zx/go/src/github.com/bytom/vendor/github.com/spf13/cobra/command.go:783 +0x2c9
github.com/bytom/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/zx/go/src/github.com/bytom/vendor/github.com/spf13/cobra/command.go:736
github.com/bytom/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x1be4e40, 0x1505288, 0x2, 0xc0001e6760)
	/home/zx/go/src/github.com/bytom/vendor/github.com/tendermint/tmlibs/cli/setup.go:83 +0x3c
main.main()
	/home/zx/go/src/github.com/bytom/cmd/bytomd/main.go:56 +0x70

```

**Comment by shenao78** [comment]
Did you start a node before？

**Comment by Paladz** [comment]
open a Bytomd while another is running
