### ISSUE TITLE
教程 发行资产失败？panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cryptodjyy** [Bytom/bytom#231]
#### Environment

- OS: MacOSX

#### Problem Description
发行资产gold：
```
./bytomcli sub-create-issue-tx 08E53AQMG0A02 a2120c2740473322cc2b0ec42191a880dc1135a61e751a9dab7e94faad1b5c41 1500 d8596073ad2720bfee02679a776a945c816d32bbd16b70cd837f9344de36d14fdf6887ba0f2ef5f71e55a811cc5678e13a2ebc5686546b063cc26688af7c6ae9 d88d03eb1a7284d9f785bf9f37993aac08923df80004dbcc21a9fcb9f9f75f429fcb8c24bb5c9e11b08fcd1b6bb8a7228fa9c6f837083b84ae0eb47a28f85d06
To build transaction:
-----------tpl:{<nil> [] false false}
----------tpl transaction:<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x44ee36e]

goroutine 1 [running]:
main.submitCreateIssueTransaction(0xc420010310, 0xc420010090, 0x5, 0x5)
	/Users/yy/Desktop/bytom_go/src/github.com/bytom/cmd/bytomcli/main.go:555 +0x57e
main.main()
	/Users/yy/Desktop/bytom_go/src/github.com/bytom/cmd/bytomcli/main.go:129 +0x271
```

挖矿的指令窗显示如下错误：

```
INFO[1133] Created asset                                 asset="&{{11678410146446783266 14711868843275430016 15857514750540061341 12357478231918206017} gold [118 107 170 32 111 11 110 28 53 140 213 100 249 64 82 55 134 193 11 139 134 92 44 44 57 11 74 222 56 71 84 133 171 235 246 203 81 81 173 105 108 0 192] [0xc4200fff80] 1 0xc4200e90c0 0xc4200e90a0}"
INFO[1133] Responses of created asset                    responses="[0xc4211ea280]"
INFO[1140] Receive request                               msg="StatusResponseMessage{Height: 6901, Hash: 751b70662a677c69eb9aa761b60deaafb93b6c4376dd34356552855ebd000000}" peerID=072404E311B1DD8D956C0C1FAA1A9571738CFC12BA27AD5C6F09088DAB24EC58
INFO[1146] Created account                               account="&{08E5G97Q00A06 bob [0xc42066e0a0] 1 0xc420596740}"
INFO[1146] Responses of created account                  responses="[0xc420618500]"
```

**Comment by liuchengxu** [comment]
`sub-create-issue-tx` has been removed in the latest release, please try with latest version.

**Comment by honhosing** [comment]
Dear developer cryptodjyy：

你好，我们是比原链团队，感谢你在1月的网络测试中提交的issues，将为你发放小小的奖励。
请回复 你的BTM收款地址，我们会在今日发放奖励。也可以添加我的个人微信：honhosing，我会邀请你进入Bytom内测群。
再次，感谢你的参与，希望之后也能多多参与我们的产品测试中，为比原链提供更多技术建议及指正。

Hi, I am from Bytom team. Thank you for you participation in Bytom network testing and submitted issues for this project. We want to send bounties to you for your testing work so please reply after this comment with attaching your BTM receiving address. Or contact me by the email: peter@bytom.io

比原链团队
Bytom Core

**Comment by cryptodjyy** [comment]
您好！
感谢比原感谢组织，我的钱包如下：

0xb37708f41e7b73d4c03413a351770d25f2d8e5ab

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
