### ISSUE TITLE
浏览器在bytomd http服务未完全启动前发请求，bytomd panic

### ISSUE THREAD

**Issue by icodezjb** [Bytom/bytom#342]
#### Environment

- OS: all
- bytom v0.4.0

#### Problem Description

2018/02/01 11:21:52 http: panic serving 127.0.0.1:57733: runtime error: invalid memory address or nil pointer dereference
goroutine 70 [running]:
net/http.(*conn).serve.func1(0xc042149360)
        /usr/local/go/src/net/http/server.go:1721 +0xd7
panic(0xc69d80, 0x16ecd50)
        /usr/local/go/src/runtime/panic.go:489 +0x2dd
github.com/bytom/blockchain.(*BlockchainReactor).ServeHTTP(0xc042553380, 0x16ac660, 0xc0425360e0, 0xc0424ea600)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:37 +0x37
github.com/bytom/node.(*waitHandler).ServeHTTP(0xc04251d1e0, 0x16ac660, 0xc0425360e0, 0xc0424ea600)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:88 +0x6c
net/http.(*ServeMux).ServeHTTP(0xc0424f78c0, 0x16ac660, 0xc0425360e0, 0xc0424ea600)
        /usr/local/go/src/net/http/server.go:2238 +0x137
github.com/bytom/blockchain.AuthHandler.func1(0x16ac660, 0xc0425360e0, 0xc0424ea300)
        /home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:143 +0x31b
net/http.HandlerFunc.ServeHTTP(0xc04251d220, 0x16ac660, 0xc0425360e0, 0xc0424ea300)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/node.RedirectHandler.func1(0x16ac660, 0xc0425360e0, 0xc0424ea300)
        /home/gavin/work/go/src/github.com/bytom/node/node.go:72 +0x72
net/http.HandlerFunc.ServeHTTP(0xc04251d2a0, 0x16ac660, 0xc0425360e0, 0xc0424ea300)
        /usr/local/go/src/net/http/server.go:1942 +0x4b
github.com/bytom/vendor/github.com/kr/secureheader.(*Config).ServeHTTP(0x16f2fe0, 0x16ac660, 0xc0425360e0, 0xc0424ea300)
        /home/gavin/work/go/src/github.com/bytom/vendor/github.com/kr/secureheader/secureheader.go:129 +0x130
net/http.serverHandler.ServeHTTP(0xc04208ec60, 0x16ac660, 0xc0425360e0, 0xc0424ea300)
        /usr/local/go/src/net/http/server.go:2568 +0x99
net/http.(*conn).serve(0xc042149360, 0x16ad0a0, 0xc04200e640)
        /usr/local/go/src/net/http/server.go:1825 +0x619
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2668 +0x2d5
2018/02/01 11:21:52 http: panic serving 127.0.0.1:57735: runtime error: invalid memory address or nil pointer dereference

**Comment by icodezjb** [comment]
fixed by merge #358
