### ISSUE TITLE
Error submitting form：Fetch error: TypeError: Network request failed

### ISSUE THREAD

**Issue by winlin** [Bytom/bytom#349]
#### Environment

- OS: Mac 10.13.2

#### Problem Description

创建 Account，不选择 Key 直接点击 Submit

NFO[0228] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
2018/02/01 22:58:28 http: panic serving 127.0.0.1:49430: runtime error: index out of range
goroutine 1147 [running]:
net/http.(*conn).serve.func1(0xc420098820)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x184f1c0, 0x20ea2c0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/bytom/blockchain/account.(*Manager).getNextAccountIndex(0xc42012d800, 0x211d9e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/gavin/work/go/src/github.com/bytom/blockchain/account/accounts.go:124 +0x27f
github.com/bytom/blockchain/account.(*Manager).Create(0xc42012d800, 0x20aa600, 0xc42c1c8600, 0x211d9e0, 0x0, 0x0, 0x1, 0xc420404848, 0x7, 0xc42c1c88d0, ...)
	/home/gavin/work/go/src/github.com/bytom/blockchain/account/accounts.go:141 +0x110
github.com/bytom/blockchain.(*BlockchainReactor).createAccount(0xc42011c820, 0x20aa600, 0xc42c1c8600, 0x211d9e0, 0x0, 0x0, 0x1, 0xc420404848, 0x7, 0xc42c1c88d0, ...)
	/home/gavin/work/go/src/github.com/bytom/blockchain/accounts.go:19 +0xde
github.com/bytom/blockchain.(*BlockchainReactor).(github.com/bytom/blockchain.createAccount)-fm(0x20aa600, 0xc42c1c8600, 0x211d9e0, 0x0, 0x0, 0x1, 0xc420404848, 0x7, 0xc42c1c88d0, 0x0, ...)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:55 +0xa5
reflect.Value.call(0x182e1a0, 0xc420510530, 0x13, 0x1930921, 0x4, 0xc42c1c8930, 0x2, 0x2, 0x0, 0xc420204900, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x182e1a0, 0xc420510530, 0x13, 0xc42c1c8930, 0x2, 0x2, 0x1, 0x2, 0x1cfef90)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/bytom/net/http/httpjson.(*handler).ServeHTTP(0xc420186380, 0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/home/gavin/work/go/src/github.com/bytom/net/http/httpjson/handler.go:60 +0x2bb
net/http.(*ServeMux).ServeHTTP(0xc42c1c8270, 0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/bytom/blockchain.(*BlockchainReactor).BuildHandler.func1(0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:121 +0x78
net/http.HandlerFunc.ServeHTTP(0xc420510920, 0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/bytom/blockchain.maxBytes.func1(0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/home/gavin/work/go/src/github.com/bytom/blockchain/reactor.go:124 +0x10a
net/http.HandlerFunc.ServeHTTP(0xc420512640, 0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4202f6540, 0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/bytom/blockchain.(*BlockchainReactor).ServeHTTP(0xc42011c820, 0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:37 +0x58
github.com/bytom/node.(*waitHandler).ServeHTTP(0xc42016cc60, 0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/home/gavin/work/go/src/github.com/bytom/node/node.go:88 +0x65
net/http.(*ServeMux).ServeHTTP(0xc42c1c82d0, 0x20a9ac0, 0xc42029cc40, 0xc420168100)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/bytom/blockchain.AuthHandler.func1(0x20a9ac0, 0xc42029cc40, 0xc420168000)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:143 +0x314
net/http.HandlerFunc.ServeHTTP(0xc42016cca0, 0x20a9ac0, 0xc42029cc40, 0xc420168000)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/bytom/node.RedirectHandler.func1(0x20a9ac0, 0xc42029cc40, 0xc420168000)
	/home/gavin/work/go/src/github.com/bytom/node/node.go:72 +0x6b
net/http.HandlerFunc.ServeHTTP(0xc42016ccc0, 0x20a9ac0, 0xc42029cc40, 0xc420168000)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/bytom/vendor/github.com/kr/secureheader.(*Config).ServeHTTP(0x20f06c0, 0x20a9ac0, 0xc42029cc40, 0xc420168000)
	/home/gavin/work/go/src/github.com/bytom/vendor/github.com/kr/secureheader/secureheader.go:129 +0x129
net/http.serverHandler.ServeHTTP(0xc4200a4e70, 0x20a9ac0, 0xc42029cc40, 0xc420168000)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420098820, 0x20aa540, 0xc420013400)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2018/02/01 22:58:28 http: panic serving 127.0.0.1:49428: runtime error: index out of range
goroutine 1077 [running]:
net/http.(*conn).serve.func1(0xc42017a820)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x184f1c0, 0x20ea2c0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/bytom/blockchain/account.(*Manager).getNextAccountIndex(0xc42012d800, 0x211d9e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/gavin/work/go/src/github.com/bytom/blockchain/account/accounts.go:124 +0x27f
github.com/bytom/blockchain/account.(*Manager).Create(0xc42012d800, 0x20aa600, 0xc42c1c8ba0, 0x211d9e0, 0x0, 0x0, 0x1, 0xc4204049b8, 0x7, 0xc42c1c8bd0, ...)
	/home/gavin/work/go/src/github.com/bytom/blockchain/account/accounts.go:141 +0x110
github.com/bytom/blockchain.(*BlockchainReactor).createAccount(0xc42011c820, 0x20aa600, 0xc42c1c8ba0, 0x211d9e0, 0x0, 0x0, 0x1, 0xc4204049b8, 0x7, 0xc42c1c8bd0, ...)
	/home/gavin/work/go/src/github.com/bytom/blockchain/accounts.go:19 +0xde
github.com/bytom/blockchain.(*BlockchainReactor).(github.com/bytom/blockchain.createAccount)-fm(0x20aa600, 0xc42c1c8ba0, 0x211d9e0, 0x0, 0x0, 0x1, 0xc4204049b8, 0x7, 0xc42c1c8bd0, 0x0, ...)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:55 +0xa5
reflect.Value.call(0x182e1a0, 0xc420510530, 0x13, 0x1930921, 0x4, 0xc42c1c8c00, 0x2, 0x2, 0x0, 0xc420204900, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x182e1a0, 0xc420510530, 0x13, 0xc42c1c8c00, 0x2, 0x2, 0x1, 0x2, 0xc420065800)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/bytom/net/http/httpjson.(*handler).ServeHTTP(0xc420186380, 0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/home/gavin/work/go/src/github.com/bytom/net/http/httpjson/handler.go:60 +0x2bb
net/http.(*ServeMux).ServeHTTP(0xc42c1c8270, 0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/bytom/blockchain.(*BlockchainReactor).BuildHandler.func1(0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:121 +0x78
net/http.HandlerFunc.ServeHTTP(0xc420510920, 0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/bytom/blockchain.maxBytes.func1(0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/home/gavin/work/go/src/github.com/bytom/blockchain/reactor.go:124 +0x10a
net/http.HandlerFunc.ServeHTTP(0xc420512640, 0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4202f6540, 0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/bytom/blockchain.(*BlockchainReactor).ServeHTTP(0xc42011c820, 0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:37 +0x58
github.com/bytom/node.(*waitHandler).ServeHTTP(0xc42016cc60, 0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/home/gavin/work/go/src/github.com/bytom/node/node.go:88 +0x65
net/http.(*ServeMux).ServeHTTP(0xc42c1c82d0, 0x20a9ac0, 0xc42029dce0, 0xc420168400)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/bytom/blockchain.AuthHandler.func1(0x20a9ac0, 0xc42029dce0, 0xc420168300)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:143 +0x314
net/http.HandlerFunc.ServeHTTP(0xc42016cca0, 0x20a9ac0, 0xc42029dce0, 0xc420168300)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/bytom/node.RedirectHandler.func1(0x20a9ac0, 0xc42029dce0, 0xc420168300)
	/home/gavin/work/go/src/github.com/bytom/node/node.go:72 +0x6b
net/http.HandlerFunc.ServeHTTP(0xc42016ccc0, 0x20a9ac0, 0xc42029dce0, 0xc420168300)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/bytom/vendor/github.com/kr/secureheader.(*Config).ServeHTTP(0x20f06c0, 0x20a9ac0, 0xc42029dce0, 0xc420168300)
	/home/gavin/work/go/src/github.com/bytom/vendor/github.com/kr/secureheader/secureheader.go:129 +0x129
net/http.serverHandler.ServeHTTP(0xc4200a4e70, 0x20a9ac0, 0xc42029dce0, 0xc420168300)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42017a820, 0x20aa540, 0xc420012840)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
2018/02/01 22:58:28 http: panic serving 127.0.0.1:49493: runtime error: index out of range
goroutine 133930 [running]:
net/http.(*conn).serve.func1(0xc42028e140)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x184f1c0, 0x20ea2c0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/bytom/blockchain/account.(*Manager).getNextAccountIndex(0xc42012d800, 0x211d9e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/gavin/work/go/src/github.com/bytom/blockchain/account/accounts.go:124 +0x27f
github.com/bytom/blockchain/account.(*Manager).Create(0xc42012d800, 0x20aa600, 0xc42c1c8f00, 0x211d9e0, 0x0, 0x0, 0x1, 0xc420404b80, 0x7, 0xc42c1c8f60, ...)
	/home/gavin/work/go/src/github.com/bytom/blockchain/account/accounts.go:141 +0x110
github.com/bytom/blockchain.(*BlockchainReactor).createAccount(0xc42011c820, 0x20aa600, 0xc42c1c8f00, 0x211d9e0, 0x0, 0x0, 0x1, 0xc420404b80, 0x7, 0xc42c1c8f60, ...)
	/home/gavin/work/go/src/github.com/bytom/blockchain/accounts.go:19 +0xde
github.com/bytom/blockchain.(*BlockchainReactor).(github.com/bytom/blockchain.createAccount)-fm(0x20aa600, 0xc42c1c8f00, 0x211d9e0, 0x0, 0x0, 0x1, 0xc420404b80, 0x7, 0xc42c1c8f60, 0x0, ...)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:55 +0xa5
reflect.Value.call(0x182e1a0, 0xc420510530, 0x13, 0x1930921, 0x4, 0xc42c1c8fc0, 0x2, 0x2, 0x0, 0xc420204900, ...)
	/usr/local/go/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x182e1a0, 0xc420510530, 0x13, 0xc42c1c8fc0, 0x2, 0x2, 0x1, 0x2, 0xc42014d800)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/bytom/net/http/httpjson.(*handler).ServeHTTP(0xc420186380, 0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/home/gavin/work/go/src/github.com/bytom/net/http/httpjson/handler.go:60 +0x2bb
net/http.(*ServeMux).ServeHTTP(0xc42c1c8270, 0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/bytom/blockchain.(*BlockchainReactor).BuildHandler.func1(0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:121 +0x78
net/http.HandlerFunc.ServeHTTP(0xc420510920, 0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/bytom/blockchain.maxBytes.func1(0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/home/gavin/work/go/src/github.com/bytom/blockchain/reactor.go:124 +0x10a
net/http.HandlerFunc.ServeHTTP(0xc420512640, 0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/usr/local/go/src/net/http/server.go:1942 +0x44
net/http.(*ServeMux).ServeHTTP(0xc4202f6540, 0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/bytom/blockchain.(*BlockchainReactor).ServeHTTP(0xc42011c820, 0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:37 +0x58
github.com/bytom/node.(*waitHandler).ServeHTTP(0xc42016cc60, 0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/home/gavin/work/go/src/github.com/bytom/node/node.go:88 +0x65
net/http.(*ServeMux).ServeHTTP(0xc42c1c82d0, 0x20a9ac0, 0xc42029ddc0, 0xc420168800)
	/usr/local/go/src/net/http/server.go:2238 +0x130
github.com/bytom/blockchain.AuthHandler.func1(0x20a9ac0, 0xc42029ddc0, 0xc420168700)
	/home/gavin/work/go/src/github.com/bytom/blockchain/rpc_reactor.go:143 +0x314
net/http.HandlerFunc.ServeHTTP(0xc42016cca0, 0x20a9ac0, 0xc42029ddc0, 0xc420168700)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/bytom/node.RedirectHandler.func1(0x20a9ac0, 0xc42029ddc0, 0xc420168700)
	/home/gavin/work/go/src/github.com/bytom/node/node.go:72 +0x6b
net/http.HandlerFunc.ServeHTTP(0xc42016ccc0, 0x20a9ac0, 0xc42029ddc0, 0xc420168700)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/bytom/vendor/github.com/kr/secureheader.(*Config).ServeHTTP(0x20f06c0, 0x20a9ac0, 0xc42029ddc0, 0xc420168700)
	/home/gavin/work/go/src/github.com/bytom/vendor/github.com/kr/secureheader/secureheader.go:129 +0x129
net/http.serverHandler.ServeHTTP(0xc4200a4e70, 0x20a9ac0, 0xc42029ddc0, 0xc420168700)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42028e140, 0x20aa540, 0xc420204d40)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
INFO[0230] Block saved on disk                           hash=b020ee6df0e29e71c8bab8eb497bb7a506118260477bb5f9b709dfdf9bcf2b46 height=125
INFO[0230] blockKeeper processed block                   hash=b020ee6df0e29e71c8bab8eb497bb7a506118260477bb5f9b709dfdf9bcf2b46 height=125 isOrphan=false
INFO[0230] blockKeeper processed block                   hash=7042a33db57ff6247dc394be4599e8f11c33d4c686fcbafd07d141d191d2cf0f height=125 isOrphan=true
INFO[0230] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0230] Skip process due to block already been handled  hash=89f407ccfcef58c6d24f9a8c29c6bc5a628522aa620c4e54b215622146e514df
INFO[0230] blockKeeper processed block                   hash=89f407ccfcef58c6d24f9a8c29c6bc5a628522aa620c4e54b215622146e514df height=123 isOrphan=false
INFO[0230] Receive request                               msg="StatusResponseMessage{Height: 18903, Hash: 843aee3873800faa35cccd95403fa71f3102725d01bde249439885224bd471ee}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0230] Receive request                               msg="BlockResponseMessage{Size: 420}" peerID=796A4EB8251FE27534F16E02C3938E349B6C24099FC283B80E9057D088E9C9B9
INFO[0230] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0231] Block saved on disk                           hash=f34fd92ef5897584922dc9260a4acc4bc427ab78acd07758919841cc1d964876 height=126
INFO[0231] blockKeeper processed block                   hash=f34fd92ef5897584922dc9260a4acc4bc427ab78acd07758919841cc1d964876 height=126 isOrphan=false
INFO[0231] blockKeeper processed block                   hash=7fd9659e968aa226e60a7c5dd176263e8812a11f22eb25c2c5e9e3e0b202ac22 height=126 isOrphan=true
INFO[0231] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0231] Skip process due to block already been handled  hash=4dffa5a5f7266e919333f539d84e8d167e008195f201f040b40c9670b13cb052
INFO[0231] blockKeeper processed block                   hash=4dffa5a5f7266e919333f539d84e8d167e008195f201f040b40c9670b13cb052 height=124 isOrphan=false
INFO[0232] Receive request                               msg="BlockResponseMessage{Size: 420}" peerID=796A4EB8251FE27534F16E02C3938E349B6C24099FC283B80E9057D088E9C9B9
INFO[0232] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0233] Block saved on disk                           hash=fef552e8a0316c2d256478668437d87294fbd038eb691754a94ec67814a77af4 height=127
INFO[0233] blockKeeper processed block                   hash=fef552e8a0316c2d256478668437d87294fbd038eb691754a94ec67814a77af4 height=127 isOrphan=false
INFO[0233] blockKeeper processed block                   hash=53d2f891640159517a080d99790f7faf5c5c3d182ccf55efc35e0acfd634c284 height=127 isOrphan=true
INFO[0233] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0233] Skip process due to block already been handled  hash=7042a33db57ff6247dc394be4599e8f11c33d4c686fcbafd07d141d191d2cf0f
INFO[0233] blockKeeper processed block                   hash=7042a33db57ff6247dc394be4599e8f11c33d4c686fcbafd07d141d191d2cf0f height=125 isOrphan=false
INFO[0233] Receive request                               msg="BlockResponseMessage{Size: 424}" peerID=796A4EB8251FE27534F16E02C3938E349B6C24099FC283B80E9057D088E9C9B9
INFO[0233] Receive request                               msg="BlockResponseMessage{Size: 288}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0234] Block saved on disk                           hash=d7ebc1b5aabbbb6ee21668b07e44d81b9ff4106559e0dcbd29afd436604defce height=128
INFO[0234] blockKeeper processed block                   hash=d7ebc1b5aabbbb6ee21668b07e44d81b9ff4106559e0dcbd29afd436604defce height=128 isOrphan=false
INFO[0234] Receive request                               msg="BlockResponseMessage{Size: 286}" peerID=5FFE736575C709F99D71522FCA9C5538DCF97834C3DEEE26D120DB0F56B3AC2A
INFO[0234] blockKeeper processed block                   hash=734daa6c4dca

**Comment by winlin** [comment]
这种前端参数检查都不做吗？相当于开发功能测试都没做，比原路还很长啊
