### ISSUE TITLE
执行两次issue-test, 第二次会出现如下错误

### ISSUE THREAD

**Issue by gguoss** [Bytom/bytom#36]
- OS: ubuntu17.04
执行两次issue-test, 第二次会出现如下错误
```bash
To create Account:
xprv_account:e84922b601818a0518a20c8d80723fd361f388b69438b79bb74571874690c377fd2898273883c6ba6d718ecd56deb33ff22fa36ff31b322b92f210870d335810
xpub_account:886d0a69a90559538ee78050deacc7f16de1815c0b680c38007b754ea2c066fffd2898273883c6ba6d718ecd56deb33ff22fa36ff31b322b92f210870d335810
account:[{acc04K82TFG00A08 alice [0xc4204f60a0] 1 0xc4204de2c0}]
To create Asset:
xprv_asset:10f1a34bed3b2e8f1cfb008f103a9ccaea7b6673e36e3b2d00ec8180837b144c6f6bbd9c157548fb1657014e07ae3df20efebb24c42ab37bfcf8fed07fca5422
xpub_asset:4577efffdd92d0c007344bbdea523586eafd86a09ebf7640a63c6d81ca5abad06f6bbd9c157548fb1657014e07ae3df20efebb24c42ab37bfcf8fed07fca5422
asset:[{{16791189614069755051 3053861012095210062 5167243687839295241 7267571559067191739} gold [118 107 170 32 230 122 234 66 4 102 32 162 250 14 82 233 47 15 95 59 68 152 220 97 158 66 44 51 168 61 176 62 32 68 92 108 81 81 173 105 108 0 192] [0xc42016e1c0] 1 0xc420170220 0xc420170240 true}]
To build transaction:
tpl:[{<nil> [] false false}]
sign-transaction error. err:missing raw tx
sign tpl:{<nil> [] false false}
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/bytom/cmd/bytomcli/example.IssueTest(0xc420020070, 0xc42000c520, 0x0, 0x0)
	/home/gavin/work/go/src/github.com/bytom/cmd/bytomcli/example/issue.go:103 +0x17ed
main.main()
	/home/gavin/work/go/src/github.com/bytom/cmd/bytomcli/main.go:122 +0x141
```

**Comment by gguoss** [comment]
是同一个input用两次的原因。 bytomcli 里的用例 是hard code。
