### ISSUE TITLE
[外部测试] 当config.toml中参数有误时，bytomd启动失败，给出来的错误信息不友好

### ISSUE THREAD

**Issue by freewind** [Bytom/bytom#656]
模拟了一下手动修改`config.toml`操作时笔误的情形，比如修改`github.com/bytom/cmd/bytomd/.bytomd/config.toml`中的`db_backend`为`leveldb2`:

```
db_backend = "leveldb2"
```

之后启动`bytomd node`，报错为：

```
$ ./bytomd node
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14e5aa2]

goroutine 1 [running]:
github.com/bytom/vendor/github.com/tendermint/tmlibs/db.NewDB(0x18c352f, 0x4, 0xc4200356b0, 0x8, 0xc4205b25f0, 0xc, 0x18c7a3a, 0x9)
	/Users/freewind/go/src/github.com/bytom/vendor/github.com/tendermint/tmlibs/db/db.go:59 +0x92
github.com/bytom/node.NewNode(0xc4200e01e0, 0xc4205bdc98)
	/Users/freewind/go/src/github.com/bytom/node/node.go:63 +0xb1
```

从这些信息很难发现到底出了什么错。建议读取config.toml时检查相应的值，并且有误的时候给出相应的提示信息

**Comment by HAOYUatHZ** [comment]
this error handling need is not that urgent 
but we will definitively bring it to world in the future.
