### ISSUE TITLE
Panicked on a Sanity Check: Error initializing DB: resource temporarily unavailable

### ISSUE THREAD

**Issue by FataliBud** [Bytom/bytom#764]
#### Environment

- OS: MacOS 10.13.3
- Bytom: SMID-64 v5.0

#### Problem Description

首先出现了下面的UPNP端口不能添加映射的问题。
```
time="2018-04-21T08:13:50+08:00" level=info msg="Local listener" ip="::" port=46656
time="2018-04-21T08:13:50+08:00" level=info msg="Getting UPNP external address"
time="2018-04-21T08:13:50+08:00" level=error msg="Could not add UPNP port mapping" error="Error 500 for AddPortMapping"
```
我执行了Ctrl+C之后，停止了程序，随后重启时，便出现了下图的情况：

![image](https://user-images.githubusercontent.com/5885519/39078415-88c6cfb6-453c-11e8-8b25-122dd12678a2.png)
```
panic: Panicked on a Sanity Check: Error initializing DB: resource temporarily unavailable

goroutine 1 [running]:
github.com/bytom/vendor/github.com/tendermint/tmlibs/common.PanicSanity(0x46a0800, 0xc42026e570)
	/Users/fsociety/go/src/github.com/bytom/vendor/github.com/tendermint/tmlibs/common/errors.go:26 +0xe4
github.com/bytom/vendor/github.com/tendermint/tmlibs/db.NewDB(0x47c30f9, 0x4, 0xc42021dfa0, 0x7, 0xc4200c0900, 0x24, 0x47c756a, 0x9)
	/Users/fsociety/go/src/github.com/bytom/vendor/github.com/tendermint/tmlibs/db/db.go:61 +0x183
github.com/bytom/node.NewNode(0xc4200e41e0, 0xc42026dc98)
	/Users/fsociety/go/src/github.com/bytom/node/node.go:63 +0xc2
github.com/bytom/cmd/bytomd/commands.runNode(0x5196840, 0xc4200b9d40, 0x0, 0x1, 0x0, 0x0)
	/Users/fsociety/go/src/github.com/bytom/cmd/bytomd/commands/run_node.go:43 +0x31
github.com/bytom/vendor/github.com/spf13/cobra.(*Command).execute(0x5196840, 0xc4200b9d20, 0x1, 0x1, 0x5196840, 0xc4200b9d20)
	/Users/fsociety/go/src/github.com/bytom/vendor/github.com/spf13/cobra/command.go:698 +0x46d
github.com/bytom/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5196620, 0x4708600, 0xc420075e01, 0xc420241180)
	/Users/fsociety/go/src/github.com/bytom/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/bytom/vendor/github.com/spf13/cobra.(*Command).Execute(0x5196620, 0xc420241180, 0xc420075f30)
	/Users/fsociety/go/src/github.com/bytom/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/bytom/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x5196620, 0x4d92610, 0x2, 0xc4200e2540)
	/Users/fsociety/go/src/github.com/bytom/vendor/github.com/tendermint/tmlibs/cli/setup.go:97 +0x4e
main.main()
	/Users/fsociety/go/src/github.com/bytom/cmd/bytomd/main.go:56 +0x78
```
我看到了一个很奇怪的现象，我的电脑用户名*不是fsociety*，这个应该是开发人员的电脑用户名吧，为什么报错显示这种问题？

**Comment by HAOYUatHZ** [comment]
你好  fsociety 是我们开发人员的的用户名 很抱歉给你造成这样的困扰

我们分析了一下问题2不是因为进程没有完全退出，而是因为目录没加好锁导致的，很感谢你指出这个问题的存在，我们正在努力解决

**Comment by HAOYUatHZ** [comment]
UPNP端口不能添加映射 是因为还没有正确实现，所以会报错。这是用于内网节点连接的，正在努力实现

**Comment by MartinBTM** [comment]
hi  add wechatid：keduo7151 to get some bytom for reward .  do not forget to note "github" when you add me
