### ISSUE TITLE
挖矿自动退出。

### ISSUE THREAD

**Issue by jidongg** [Bytom/bytom#835]
#### Environment

- OS: win10

#### Problem Description

这里不能发图，截图已发给测试群思想的苇草。

**Comment by HirayClay** [comment]
@jidongg 可以发截图的，
![5 1m 0rqhde 2ahq 3 mk](https://user-images.githubusercontent.com/12825256/39223786-7cecfb60-4876-11e8-838c-5886e04906bb.png)可以直接把图拖过来或者‘slecting them‘

**Comment by lizistorm** [comment]
同样的问题，每次运行约4~5个小时就会退出，错误信息：

```
time="2018-04-25T03:27:36+08:00" level=info msg="Dialing peer" address="125.120.74.34:46658"
time="2018-04-25T03:27:39+08:00" level=info msg="Failed to dial peer" address="125.120.74.34:46658" error="Error creating peer: dial tcp 125.120.74.34:46658: i/o timeout"
time="2018-04-25T03:27:39+08:00" level=info msg="Dialing peer" address="68.194.134.25:46657"
time="2018-04-25T03:27:42+08:00" level=info msg="Failed to dial peer" address="68.194.134.25:46657" error="Error creating peer: dial tcp 68.194.134.25:46657: i/o timeout"
time="2018-04-25T03:27:42+08:00" level=info msg="Dialing peer" address="218.3.169.250:46657"
time="2018-04-25T03:27:45+08:00" level=info msg="bk peer num:2 sw peer num:2 [Peer{MConn{58.246.134.226:46657} 19C7F43CA3D8 out} Peer{MConn{47.100.105.165:46657} 0DFF1B28656A out}]"
time="2018-04-25T03:27:45+08:00" level=info msg="Failed to dial peer" address="218.3.169.250:46657" error="Error creating peer: dial tcp 218.3.169.250:46657: i/o timeout"
time="2018-04-25T03:27:45+08:00" level=info msg="Dialing peer" address="123.249.0.160:46657"
time="2018-04-25T03:27:48+08:00" level=info msg="Failed to dial peer" address="123.249.0.160:46657" error="Error creating peer: dial tcp 123.249.0.160:46657: i/o timeout"
time="2018-04-25T03:27:48+08:00" level=info msg="No addresses to dial. Sending pexRequest to random peer" peer="Peer{MConn{47.100.105.165:46657} 0DFF1B28656A out}"
time="2018-04-25T03:27:48+08:00" level=info msg="Stopping peer gracefully"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x68 pc=0x9722be]

goroutine 115 [running]:
github.com/bytom/p2p.(*Switch).stopAndRemovePeer(0x0, 0xc04228e120, 0x0, 0x0)
        E:/Project/go/src/github.com/bytom/p2p/switch.go:489 +0x3e
github.com/bytom/p2p.(*Switch).StopPeerGracefully(0x0, 0xc04228e120)
        E:/Project/go/src/github.com/bytom/p2p/switch.go:485 +0x84
github.com/bytom/p2p.(*PEXReactor).RequestPEX(0xc04210fb20, 0xc04228e120)
        E:/Project/go/src/github.com/bytom/p2p/pex_reactor.go:168 +0xb3
github.com/bytom/p2p.(*PEXReactor).ensurePeers(0xc04210fb20)
        E:/Project/go/src/github.com/bytom/p2p/pex_reactor.go:318 +0xa30
github.com/bytom/p2p.(*PEXReactor).ensurePeersRoutine(0xc04210fb20)
        E:/Project/go/src/github.com/bytom/p2p/pex_reactor.go:222 +0x9b
created by github.com/bytom/p2p.(*PEXReactor).OnStart
        E:/Project/go/src/github.com/bytom/p2p/pex_reactor.go:76 +0x5a
```

**Comment by blue68** [comment]
@lizistorm， 同样的问题

**Comment by HAOYUatHZ** [comment]
itz not caused by mining

**Comment by HAOYUatHZ** [comment]
1.0.0 是否还存在这个问题呢？相信已经被 solved？   没有问题的话我就关掉这个issue啦

**Comment by HAOYUatHZ** [comment]
1.0.0 是否还存在这个问题呢？相信已经被 solved？   没有问题的话我就关掉这个issue啦

**Comment by HAOYUatHZ** [comment]
不好意思  1.0.0 确实还存在空指针问题
这个问题我们在 别的branch已经修复
后面会发新版版
